package org.openmrs.module.supply.utils;

public class OperationConstants {
	
	////////////////// Operation Type Const
	public static final String INVENTORY_OPERATION = "INVENTORYOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String PARTIAL_INVENTORY_OPERATION = "INVENTORYPARTIALOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String INVENTORY_POSITIVE_ADJUST_OPERATION = "INVENTORYADJUSTPOSITIVEOOOOOOOOOOOOOOO";
	
	public static final String INVENTORY_NEGATIVE_ADJUST_OPERATION = "INVENTORYADJUSTNEGATIVEOOOOOOOOOOOOOOO";
	
	public static final String RECEPTION_OPERATION = "RECEPTIONOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String RECEPTION_RETURN_OPERATION = "RECEPTIONRETURNOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String PRODUCT_RETURN_IN_OPERATION = "PRODUCTRETURNINOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String PRODUCT_RETURN_OUT_OPERATION = "PRODUCTRETURNOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String TRANSFER_OUT_OPERATION = "TRANSFEROUTOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String TRANSFER_IN_OPERATION = "TRANSFERINOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String EXPIRY_OPERATION = "EXPIRYOUTOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String THIEF_OPERATION = "THIEFOUTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String DESTROYED_OPERATION = "DESTROYEDOUTOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String SPOILED_OPERATION = "SPOILEDOUTOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String OTHER_OUT_OPERATION = "OTHEROUTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String DONATION_OPERATION = "DONATIONENTRYOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String REPORT_OPERATION = "REPORTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String URGENT_REPORT_OPERATION = "URGENTREPORTOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String DISPENSATION_OPERATION = "DISPENSATIONOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	public static final String DISTRIBUTION_OPERATION = "DISTRIBUTIONOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	//////////////////// Operation Attribute Const
	//	public static final String I_ATTRIBUTEN = "DISTRIBUTIONOOOOOOOOOOOOOOOOOOOOOOOOOO";
	
	/// Notification Constants
	
	public static final String REPORT_SUBMISSION_NOTIFICATION = "SOUMISSION DE RAPPORT";
	
	public static final String REPORT_TREATMENT_NOTIFICATION = "TRAITEMENT DE RAPPORT";
	
	public static final String REPORT_REJECTED_NOTIFICATION = "REJET DE RAPPORT";
	
	public static final String TRANSFER_OUT_NOTIFICATION = "TRANSFERT SORTANT";
	
	public static final String TRANSFER_IN_NOTIFICATION = "TRANSFERT ENTRANT";
	
	public static final String PRODUCT_RETURN_IN_NOTIFICATION = "RETOUR DE PRODUITS";
	
	public static final String PRODUCT_RUPTURE_NOTIFICATION = "RUPTURE DE PRODUIT";
}
